highschooledu/highschooledu/apps/core/urls.py
from django.urls import path
from .views import (home, update_field_model, post_ajax_create_action)

app_name = "core"

urlpatterns = [
    path('', home, name='home'),
    path('post_ajax_create_action', post_ajax_create_action, name='post_ajax_create_action'),
    path('update_field_model', update_field_model, name='update_field_model'),
]

highschooledu/highschooledu/apps/users/urls.py
from django.conf.urls import url
from django.urls import path, include
from .views import (show_content, show_sub_content,
                    DeleteInstitution, InstitutionsView, InstitutionView, CreateInstitution, UpdateInstitution,
                    edit_user_profile, user_delete)

app_name = "users"

urlpatterns = [
    path('show_content', show_content, name='show_content'),
    path('show_sub_content', show_sub_content, name='show_sub_content'),
    path('institutions', InstitutionsView.as_view(), name='list_institution'),
    path('CreateInstitutions/', CreateInstitution.as_view(), name='create_institution'),
    path('edit_user_profile/', edit_user_profile, name='edit_user_profile'),
    path('user_delete/', user_delete, name='user_delete'),

    # url(r'^institutions$', InstitutionsView.as_view(), name='list_institution'),

    url(r'^institutions/(?P<pk>\d+)/$', InstitutionView.as_view(), name='detailed_institution'),
    # url(r'^CreateInstitutions/$', CreateInstitution.as_view(), name='create_institution'),
    url(r'^UpdateInstitutions/(?P<pk>\d+)/$', UpdateInstitution.as_view(), name='update_institution'),
    url(r'^DeleteInstitutions/(?P<pk>\d+)/$', DeleteInstitution.as_view(), name='delete_institution'),

    # url(r'^edit_user_profile/$', edit_user_profile, name='edit_user_profile'),
    #
]

highschooledu/highschooledu/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]


urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path(r'core/', include('highschooledu.apps.core.urls')),
    # path(r'e/', include('highschooledu.apps.education.urls')),
    path(r'c/', include('highschooledu.apps.checkcashingchicago.urls')),
    path(r'p/', include('highschooledu.apps.portfolio.urls')),

    path(r'search/', include('highschooledu.apps.search.urls')),
    path(r'webcompanies/', include('highschooledu.apps.webcompanies.urls')),
    path("", include("cms.urls"))
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

highschooledu/highschooledu/apps/users/models.py
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse
from filer.fields.image import FilerImageField
# from ckeditor.fields import RichTextField  # ,
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.translation import ugettext_lazy as _, get_language


class Institution(models.Model):
    TYPES = (
        (0, 'Other'),
        (1, 'University'),
        (2, 'College'),
        (3, 'Company'),
        (4, 'Private'),
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=100, default='', blank=True)
    type = models.IntegerField(default=1, choices=TYPES)

    def get_absolute_url(self):
        return reverse('users:detailed_institution', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Profile(models.Model):
    class Meta:
        verbose_name = _('profile')
        verbose_name_plural = _('profiles')
        ordering = ['-created']

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_confirmed = models.BooleanField(default=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                primary_key=True, related_name='academics')
    short_bio = RichTextUploadingField(_('short_bio'), blank=True, null=True)
    bio = RichTextUploadingField(_('bio'), blank=True, null=True)
    #
    address = models.CharField(_('address'), max_length=128, default='', blank=True)
    zip = models.CharField(_('zip'), max_length=20, default='', blank=True)
    city = models.CharField(_('city'), max_length=100, default='', blank=True)
    country = models.CharField(_('country'), max_length=100, default='', blank=True)
    #
    phone = models.CharField(_('phone'), max_length=20, default='', blank=True)
    website = models.URLField(_('website'), default='http://academycity.org', blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    institution = models.ForeignKey(Institution, null=True, blank=True, on_delete=models.PROTECT)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return self.user.get_full_name()

highschooledu/highschooledu/apps/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import (Profile)


class UserEditForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'email'
        )


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image', 'date_of_birth', 'short_bio', 'bio',
                  'address', 'zip', 'city', 'country',
                  'phone', 'website', 'institution')

highschooledu/highschooledu/apps/users/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse, reverse_lazy
from .models import (Institution, Profile,)
from ..courses.models import (Department, GeneralLedger, TrialBalance, Order,
                              OrderItem, CourseSchedule, CourseScheduleUser)
from .forms import (ProfileEditForm, UserEditForm)
from ..actions.models import Action
from ..courses.models import (CourseScheduleUser, Order, TrialBalance,
                              Course, Section, SubSection)
from ..core.accounting import update_trial_balance
from django.utils.translation import ugettext_lazy as _, get_language
from django.db.models import Q

import pandas as pd
from ..core.sql import SQL
from ..courses.models import Coupon, CourseScheduleUser
from ..core.sql import SQL
from ..core.filesystem import FS
from django.contrib.auth import get_user_model
from django.http import JsonResponse


def show_sub_content(request):
    sub_page = request.POST.get('sub_page')
    if sub_page == "process_trial_balance":
        period_type = request.POST.get('period_type')
        update_trial_balance(period_type)
        period_type_ = 1
        if '3' in period_type:
            period_type_ = 3
        elif '2' in period_type:
            period_type_ = 2

        trial_balance_1 = TrialBalance.objects.filter(flow_type=1).filter(period_type=period_type_)
        trial_balance_2 = TrialBalance.objects.filter(flow_type=2).filter(period_type=period_type_)
        return render(request, 'users/_process_trial_balance.html',
                      {'period_type': period_type,
                       'trial_balance_1': trial_balance_1,
                       'trial_balance_2': trial_balance_2,
                       })
    elif sub_page == "admin_role_management_courses":
        report = request.POST.get('report')
        departments = Department.objects.all().filter(translations__language_code=get_language()).order_by('order')
        return render(request, 'users/_admin_role_management_courses.html', {'departments': departments})

    elif sub_page == "instructor_role_management_courses":
        report = request.POST.get('report')
        ics = CourseSchedule.objects.filter(instructors=request.user).all()
        print(ics)
        return render(request, 'users/_instructor_role_management_courses.html', {'course_schedules': ics})
    elif sub_page == "student_role_management_courses":
        report = request.POST.get('report')
        if report == 'courses':
            my_course_schedule_user = \
                CourseScheduleUser.objects.filter(user=request.user).filter(course_schedule__active=True)
            my_course_schedule_user_completed = \
                CourseScheduleUser.objects.filter(user=request.user).filter(course_schedule__active=False)

            my_orders = Order.objects.filter(user=request.user)
            return render(request, 'users/_student_role_management_courses.html',
                          {'my_course_schedule_user': my_course_schedule_user,
                           'my_orders': my_orders,
                           'my_course_schedule_user_completed': my_course_schedule_user_completed
                           })
    elif sub_page == "admin_role_management_maintenance":
        report = request.POST.get('report')
        print(report)
        general_ledger = GeneralLedger.objects.all()
        trial_balance = TrialBalance.objects.all()
        order = Order.objects.all()
        order_item = OrderItem.objects.all()
        course_schedule = CourseSchedule.objects.all()
        course_schedule_user = CourseScheduleUser.objects.all()
        coupon = Coupon.objects.all()
        return render(request, 'users/_admin_role_management_maintenance.html',
                      {'general_ledger': general_ledger,
                       'trial_balance': trial_balance,
                       'order': order,
                       'order_item': order_item,
                       'course_schedule': course_schedule,
                       'course_schedule_user': course_schedule_user,
                       'coupon': coupon,
                       })
    elif sub_page == "admin_role_management_clean_accounting_registrations":
        print(1111)
        # report = request.POST.get('report')
        # print(report)
        # sql = SQL()
        # print('-1-')
        # sql.exc_sql("""truncate table courses_trialbalance""", ())
        # print('-12-')
        # sql.exc_sql("""truncate table courses_generalledger""", ())
        # print('-13-')
        # sql.exc_sql("""
        #             truncate table courses_coupon, courses_orderitem,
        #             courses_order, courses_coursescheduleuser, courses_courseschedule_instructors,
        #             courses_courseschedule""", ())
        print('-15-')
        return render(request, 'users/_admin_role_management_car.html', {'results': 'ok'})
    elif sub_page == "admin_role_management_registered_users":
        report = request.POST.get('report')
        User = get_user_model()
        if report == 'signed_up':
            users = User.objects.order_by('-date_joined')
        elif report == 'not_registered_for_course':
            users = User.objects.filter(course_schedule_users__isnull = True).order_by('-date_joined')
        return render(request, 'users/_admin_role_management_registered_users.html', {'users': users})

    elif sub_page == "admin_role_management_file_system":
        report = request.POST.get('report')
        fs = FS()
        if report == 'file_system':
            fs_info = fs.get_info_for(path="/")
            return render(request, 'users/_admin_role_management_file_system.html', {'fs_info': fs_info})
        if report == 'backup':
            path = settings.DBBACKUP_STORAGE_OPTIONS['location']
            files = fs.get_files_in(path)
            return render(request, 'users/_admin_role_management_backup.html', {'path': path, 'files': files})


    elif sub_page == "admin_role_management_documentations":
        report = request.POST.get('report')
        if report == 'academycity':
            return render(request, 'users/_admin_role_management_documentations.html', {})
    elif sub_page == "admin_role_management_research":
        report = request.POST.get('report')
        if report == 'all':
            return render(request, 'users/_admin_role_management_research.html', {'report': report})

    return render(request, 'users/_show_content.html', {'page': sub_page})


def show_content(request):
    page=request.POST.get('page')
    if page == "student_role_management":
        return render(request, 'users/_student_role_management.html', {})
    elif page == "admin_role_management":
        return render(request, 'users/_admin_role_management.html', {})

    # elif page == "my_courses":
    #     my_course_schedule_user = \
    #         CourseScheduleUser.objects.filter(user=request.user).filter(course_schedule__active=True)
    #     my_course_schedule_user_completed = \
    #         CourseScheduleUser.objects.filter(user=request.user).filter(course_schedule__active=False)
    #     my_orders = Order.objects.filter(user=request.user)
    #     return render(request, 'users/_my_course_schedule_user.html',
    #                   {'my_course_schedule_user': my_course_schedule_user,
    #                    'my_orders': my_orders,
    #                    'my_course_schedule_user_completed': my_course_schedule_user_completed
    #                    })
    elif page == "my_actions":
        my_actions = Action.objects.filter(user=request.user)
        return render(request, 'users/_my_actions.html', {'my_actions': my_actions})
    elif page == "all_actions":
        # all_actions = Action.objects.all()
        verbs_ = list(Action.objects.values_list('verb', flat=True))
        verbs_ = list(set(verbs_))
        print(verbs_)
        Action.objects.filter(object_id__isnull=False)
        print('users/_all_actions.html')

        return render(request, 'users/_all_actions.html', {
            'verbs': verbs_
            # 'all_actions': all_actions
        })
    elif page == "courses_actions":
        page = request.POST.get('page')
        by = 'a.created'
        filter = ''
        if request.POST.get('filter') is not None:
            filter = request.POST.get('filter')
            if filter == '':
                by = request.POST.get('by')
            else:
                filter_where = request.POST.get('filter_where')
                filter = ' and ' + filter_where + ' = ' + request.POST.get('filter')
        # print('-----')
        # print(page)
        # print(filter)
        # print(by)
        # print('-----')
        sql = SQL()
        squery = '''
                SELECT a.created, a.verb, ss.id, s.id, c.id, cs.id, au.id
                FROM actions_Action a, courses_SubSection ss, courses_Section s, courses_course c, auth_user au,
                courses_CourseScheduleUser csu, courses_CourseSchedule cs
                WHERE a.object_id = ss.id
                and ss.section_id = s.id
                and s.course_id = c.id
                and a.user_id = au.id
                and cs.course_id = c.id                
                and csu.course_schedule_id = cs.id                
                and csu.user_id = au.id
                ''' + filter + " order by " + by
        # print(squery)
        results = sql.exc_sql(squery, [], verb='select')
        results = pd.DataFrame(results, columns=['created', 'verb', 'SubSection', 'Section', 'Course', 'Class', 'User'])
        return render(request, 'users/_courses_actions.html', {
            'df': results
        })

    elif page == "accountant_close_the_books":

highschooledu/highschooledu/apps/users/templates/users/_admin_role_management_backup.html
{% extends "courses/course_schedule/formset_base.html" %}
{% load static i18n cms_tags menu_tags sekizai_tags thumbnail %}


{% block content %}
<div onclick="btn_users(event)">
<table class="w3-table-all w3-hoverable" style="width:80%; margin-left:5px;">
    <thead><th></th><th>Memory(GBit)</th></thead>
    <tbody>
    {% for f in files%}
        <tr><td><a href="{% static 'postgres_backup/' %}{{f.0}}" >{{ f.0 }} </a></td><td>{{ f.1 }}</td></tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

highschooledu/highschooledu/apps/users/templates/users/_admin_role_management_courses_schedule_user.html
<div onclick="btn_course_schedule_activation(event)">
    <h4 style="color:blue"><u>Scheduled courses and users for course: {{ course_schedule.course.name }}
        -- Group: {{ course_schedule.name }}</u></h4>
    <h5 style="margin-left:20px;color:green">From: {{ course_schedule.start_date }}   To: {{ course_schedule.end_date }}</h5>
    <h5 style="margin-left:20px;color:green">Num students enrolled: {{ course_schedule.number_of_students_enrolled}}</h5>
    <h5 style="margin-left:20px;color:green">Num students assigned: {{ course_schedule.number_of_students_assigned}}</h5>
    <h5 style="margin-left:20px;color:green">Num of teams left: {{ course_schedule.number_of_teams_left}}</h5>

  <table class="w3-table-all w3-hoverable" style="width:80%; margin-left:5px;">
    <thead>
      <tr class="w3-light-blue">
          <th style="border: 1px solid black;width:2%">#</th>
          <th style="border: 1px solid black;width:10%">Team</th>
          <th style="border: 1px solid black;width:10%">Student Name</th>
          <th style="border: 1px solid black;width:10%">Email</th>
          <th style="border: 1px solid black;width:3%">Delete</th>
          <th style="border: 1px solid black;width:10%">Status-Active?</th>
          <th style="border: 1px solid black;width:10%">Graduated?</th>
          <th style="border: 1px solid black;width:10%">print Cert/Diploma</th>
      </tr>
    </thead>
      {% for course_course_schedule in course_schedule.course_course_schedules.all %}
        <tr>
            <td style="padding-right:3px">
                <span>{{ forloop.counter }}</span>
            </td>
            <td>
                    <span>{{ course_course_schedule.team.name }}</span>
            </td>
            <td>
                    <span>{{ course_course_schedule.user.get_full_name }}</span>
            </td>
            <td>
                <a href="#" >
                    <span type="course_schedule_setup_user_email" data-id="{{course_course_schedule.user.id}}">
                        {{ course_course_schedule.user.email }}
                    </span>
                </a>
            </td>
            <td>
                <a href="#" data-slug="{{course_course_schedule.slug}}">
                    <i class="fa fa-trash-alt" type="class_schedule_delete"></i>
                </a>
            </td>
            <td>
                <span id="{{ course_course_schedule.slug }}">
                  {% if course_course_schedule.active %}
                  Active
                  {% else %}
                  Not Active
                  {% endif %}
                </span> &nbsp;
                <a href="#" data-slug="{{course_course_schedule.slug}}" type="class_schedule"
                  data-action="{% if course_course_schedule.active %}de{% endif %}activate" >
                  {% if course_course_schedule.active %}
                  Deactivate
                  {% else %}
                  Activate
                  {% endif %}
                </a>
            </td>


            <td>
                <span id="{{ course_course_schedule.slug }}">
                  {% if course_course_schedule.graduated %}
                  Graduated
                  {% else %}
                  Not Graduated
                  {% endif %}
                </span> &nbsp;
                <a href="#" data-slug="{{course_course_schedule.slug}}" type="class_schedule_graduate"
                  data-action="{% if not course_course_schedule.graduated %}de{% endif %}graduated" >
                  {% if course_course_schedule.graduated %}
                  DeGraduate
                  {% else %}
                  Graduate
                  {% endif %}
                </a>
            </td>
            <td>
              {% if course_course_schedule.graduated%}
                <a href="{{ course_course_schedule.get_diploma_url }}" target="_blank">
                  <span class="badge badge-pill badge-primary">
                    {% if course_schedule.certificate_number < 100 %}
                      Show Certificate {{course_schedule.certificate_number}}<br/>
                    {% else %}
                      Show Diploma
                    {% endif %}
                  </span>
                </a>
              {% else %}
                Not Graduated Yet
              {% endif %}
            </td>
        </tr>
      {% endfor %}
  </table>
</div>

highschooledu/highschooledu/apps/users/templates/users/_admin_role_management_maintenance.html
{% load static i18n cms_tags menu_tags sekizai_tags thumbnail %}
<!--
https://fontawesome.com/icons?d=gallery&c=editors,education,users-people&m=free
-->
<div class="w3-responsive">
  <div class="row">
    <div class="col-sm-6 navbar_" style="background-color:lavenderblush;" onclick="btnClickDepCourse(event)">
        {% include "users/_create_table_include.html" with table=trial_balance name="trial_balance" %}
        {% include "users/_create_table_include.html" with table=general_ledger name="General Ledger" %}
        {% include "users/_create_table_include.html" with table=order_item name="order_item" %}
        {% include "users/_create_table_include.html" with table=order name="order" %}
        {% include "users/_create_table_include.html" with table=course_schedule_user name="course_schedule_user" %}
        {% include "users/_create_table_include.html" with table=course_schedule name="course_schedule" %}
        {% include "users/_create_table_include.html" with table=coupon name="Coupon" %}
    </div>
  </div>
</div>

highschooledu/highschooledu/apps/users/templates/users/_admin_role_management_research.html
{% extends "courses/course_schedule/formset_base.html" %}
{% load static i18n cms_tags menu_tags sekizai_tags thumbnail %}

{% block content %}
<div >
    <b><u>Research: {{ report }}</u></b><br/>
    <a href="{% url 'research:potential' %}">Potential</a>
</div>
{% endblock %}

highschooledu/highschooledu/apps/users/templates/users/_courses_actions.html
{% load static i18n cms_tags menu_tags sekizai_tags thumbnail %}
{% load core_tags %}

<style>
table {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
}

tr:nth-child(even){background-color: #ccddff;}
tr:hover {background-color: #e6eeff;}

th {
  text-align: center;
  padding: 5px;
  background-color: #4d88ff;
  color: white;
}

td {
  border: 1px solid #ddd;
  padding: 3px;
  text-align: right;
}

a { color: black }

.column {
  float: left;
  padding: 5px;
}

.left {
  width: 10%;
}

.middle {
  width: 7%;
}

.pointer {cursor: pointer; text-decoration: underline;}

</style>
<br/>

{% if LANGUAGE_CODE == "ar" %}
<div id="action-list" dir="RTL"style="text-align: right;" class="row">
{% else %}
<div id="action-list" dir="LTR" class="row">
{% endif%}

<div class="column left" style="height:140px; overflow: scroll;">
  <table>
    <thead>
    <th>Verb</th>
    </thead>
  {% for r in df.verb.unique %}
  <tr><td class="pointer" style="text-align: center">
    <a href="#" onclick="show_content_click(event)" data-page="courses_actions"
     data-filter="'{{ r }}'" data-filter_where="a.verb" data-by="" >{{ r }}</a>
    </td></tr>
  {% endfor %}
  </table>
</div>

<div class="column middle" style="height:140px; overflow: scroll;">
  <table>
    <thead>
    <th>Course</th>
    </thead>
  {% for r in df.Course.unique %}
  <tr><td class="pointer" style="text-align: center">
    <a href="#" onclick="show_content_click(event)" data-page="courses_actions"
     data-filter="{{ r }}" data-filter_where="c.id" data-by="" >{{ r }}</a>
    </td></tr>
  {% endfor %}
  </table>
</div>

<div class="column middle" style="height:140px; overflow: scroll;">
  <table>
    <thead>
    <th>Classes</th>
    </thead>
  {% for r in df.Class.unique %}
  <tr><td class="pointer" style="text-align: center">
    <a href="#" onclick="show_content_click(event)" data-page="courses_actions"
     data-filter="{{ r }}" data-filter_where="cs.id" data-by="" >{{ r }}</a>
    </td></tr>
  {% endfor %}
  </table>
</div>

<div class="column middle" style="height:140px; overflow: scroll;">
  <table>
    <thead>
    <th>Users</th>
    </thead>
  {% for r in df.User.unique %}
  <tr><td class="pointer" style="text-align: center">
    <a href="#" onclick="show_content_click(event)" data-page="courses_actions"
     data-filter="{{ r }}" data-filter_where="au.id" data-by="" >{{ r }}</a>
    </td></tr>
  {% endfor %}
  </table>
</div>
</div>

<div style="height:350px; overflow: scroll;width: 50%">
    <div>
      <table style="position: fixed;">
        <thead>
        <th style="width:200px">Created</th>
        <th style="width:150px">Verb</th>
        <th style="width:100px">SubSection</th>
        <th style="width:70px">Section</th>

        <th style="width:70px"><a href="#" onclick="show_content_click(event)" data-page="courses_actions"
         data-filter="" data-by="c.id, s.id, ss.id" >Course</a></th>
        <th style="width:70px"><a href="#" onclick="show_content_click(event)" data-page="courses_actions"
         data-filter="" data-by="cs.id" >Classes</a></th>
        <th style="width:70px"><a href="#" onclick="show_content_click(event)" data-page="courses_actions"
         data-filter="" data-by="au.id" >User</a></th>
        </thead>
      </table>
    </div>
    <br/>
    <div style="margin-top: 12px;border: 1px solid black;">
      <table>
      <tbody>
        {% for r in df.itertuples %}
        <tr><td style="width:200px">{{ r.created }}</td><td style="width:150px">{{ r.verb }}</td>
            <td style="width:100px">{{ r.SubSection }}</td><td style="width:70px">{{ r.Section }}</td>
            <td style="width:70px">{{ r.Course }}</td><td style="width:70px">{{ r.Class }}</td>
            <td style="width:70px">{{ r.User }}</td></tr>
        {% endfor %}
      </tbody>
      </table>
    </div>
</div>

<script>

  show_content_click = function(event)
  {
      event.preventDefault();
      elm = event.target
      page_ = elm.getAttribute('data-page')
      filter_ = elm.getAttribute('data-filter')
      filter_where_ = elm.getAttribute('data-filter_where')
      by_ = elm.getAttribute('data-by')
      //alert(by_)
      $.post('{% url "users:show_content" %}',
        {
          page: page_,
          filter: filter_,
          by: by_,
          filter_where: filter_where_
        },
        function(data){
        //alert(data)
            $('#page_content').empty().append(data)
            closeNav();
        }
      );
  }
</script>

highschooledu/highschooledu/apps/users/templates/users/_my_actions.html
{% load static i18n cms_tags menu_tags sekizai_tags thumbnail %}

<h2>My Actions</h2>
<div id="action-list">
  {% for action in my_actions %}
    {% include "users/_my_action_detail.html"%}
  {% endfor %}
</div>

highschooledu/highschooledu/apps/users/templates/users/_show_content.html
{% load static i18n cms_tags menu_tags sekizai_tags thumbnail %}
<hr/>
<h1 >{{ page }}</h1>

highschooledu/highschooledu/apps/users/templates/users/institution_update_form.html
{% extends "academycity/base_user.html" %}

{% block title %}
    <title>Update Institution</title>
{% endblock title %}

{% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <b><input type="submit" value="Update" style="color:blue" />
        <input type="button" value="Cancel" style="color:red"
                  onclick="window.history.go(-1);"/></b>
    </form>
</div>
{% endblock %}