highschooledu/highschooledu/apps/checkcashingchicago/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (home, get_location, location_detail, post_contact_us, members_area_detail,
                    post_password)

app_name = 'checkcashingchicago'

urlpatterns = [
    path('', home, name='home'),
    path('get_courses', get_location, name='get_location'),
    path('location_detail/<slug:slug>/', location_detail, name='location_detail'),
    path('members_area_detail', members_area_detail, name='members_area_detail'),
    path('post_contact_us', post_contact_us, name='post_contact_us'),
    path('post_password', post_password, name='post_password'),
]

highschooledu/highschooledu/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]


urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path(r'core/', include('highschooledu.apps.core.urls')),
    # path(r'e/', include('highschooledu.apps.education.urls')),
    path(r'c/', include('highschooledu.apps.checkcashingchicago.urls')),
    path(r'p/', include('highschooledu.apps.portfolio.urls')),

    path(r'search/', include('highschooledu.apps.search.urls')),
    path(r'webcompanies/', include('highschooledu.apps.webcompanies.urls')),
    path("", include("cms.urls"))
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

highschooledu/highschooledu/apps/checkcashingchicago/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from cms.models.fields import PlaceholderField


class CheckCashingWeb(models.Model):

    class Meta:
        verbose_name = _('check cashing')
        verbose_name_plural = _('check cashing')
        ordering = ['order']

    order = models.IntegerField(default=1000, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    domain_name = models.CharField(max_length=100, null=True, blank=True)
    main_image = models.ImageField(upload_to='checkcashing/', blank=True, null=True)
    logo_image = models.ImageField(upload_to='checkcashing/', blank=True, null=True)
    background_location_image = models.ImageField(upload_to='location/', blank=True, null=True)
    background_currency_image = models.ImageField(upload_to='currency/', blank=True, null=True)
    main_title = models.CharField(max_length=100, null=True)
    footer_main_title = models.CharField(max_length=100, null=True)
    main_sub_title = models.CharField(max_length=100, null=True)
    location_title = models.CharField(max_length=100, null=True)
    partner_title = models.CharField(max_length=100, null=True)
    main_sub_description = models.CharField(max_length=500, null=True)
    check_cashing_application = models.FileField(upload_to='checkcashing/', blank=True, null=True)
    application_for_employment = models.FileField(upload_to='checkcashing/', blank=True, null=True)
    copy_right_year = models.CharField(max_length=4, null=True)
    contact_us_email = models.CharField(max_length=100, null=True)
    members_password = models.CharField(max_length=100, default='101')

    def __str__(self):
        return self.name


class LocationRegion(models.Model):

    class Meta:
        verbose_name = _('location_region')
        verbose_name_plural = _('location_regions')
        ordering = ['order']

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, related_name='location_regions')
    order = models.IntegerField(default=1000, blank=True)
    region_title = models.CharField(max_length=100, null=True)
    slug = models.SlugField(max_length=250, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.region_title)
        super(LocationRegion, self).save(*args, **kwargs)

    def __str__(self):
        return self.region_title


class Location(models.Model):

    class Meta:
        verbose_name = _('location')
        verbose_name_plural = _('locations')
        ordering = ['order']

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE,
                                          related_name='locations')
    region = models.ForeignKey(LocationRegion, on_delete=models.CASCADE, blank=True, null=True,
                               related_name='region_locations')
    order = models.IntegerField(default=1000, blank=True)
    image = models.ImageField(upload_to='location/', blank=True, null=True)
    location_heading = models.CharField(max_length=100, null=True)
    location_detail_title = models.CharField(max_length=100, null=True)
    address1 = models.CharField(max_length=50, null=True)
    address2 = models.CharField(max_length=50, null=True)
    address3 = models.CharField(max_length=50, null=True)
    address4 = models.CharField(max_length=50, null=True)
    working_hours1 = models.CharField(max_length=50, blank=True, null=True)
    working_hours2 = models.CharField(max_length=50, blank=True, null=True)
    working_hours3 = models.CharField(max_length=50, blank=True, null=True)
    working_hours4 = models.CharField(max_length=50, blank=True, null=True)
    data_ajax_id = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(max_length=250, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.location_heading)
        super(Location, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('checkcashingchicago:location_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.location_heading


class Service(models.Model):

    class Meta:
        verbose_name = _('service')
        verbose_name_plural = _('services')
        ordering = ['order']

    location = models.ManyToManyField(Location, related_name='services')
    order = models.IntegerField(default=1000, blank=True)
    title = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=800, null=True)


class Currency(models.Model):

    class Meta:
        verbose_name = _('currency')
        verbose_name_plural = _('currencies')
        ordering = ['order']

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, default=1,
                                          related_name='currencies')
    order = models.IntegerField(default=1000, blank=True)
    image = models.ImageField(upload_to='currency/', blank=True, null=True)
    currency_header = models.CharField(max_length=100, null=True)
    currency_description = models.CharField(max_length=500, null=True)
    image_id = models.IntegerField(default=0)
    currency_loop = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)


class Partner(models.Model):

    class Meta:
        verbose_name = _('partner')
        verbose_name_plural = _('partners')
        ordering = ['order']

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, default=1,
                                          related_name='partners')
    order = models.IntegerField(default=1000, blank=True)
    partner_image = models.ImageField(upload_to='partner/', blank=True, null=True)
    partner_description = models.CharField(max_length=100, null=True)
    partner_link = models.CharField(max_length=100, null=True)
    image_id = models.IntegerField(default=0)
    image_width = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)


class ContactUsMessages(models.Model):

    class Meta:
        verbose_name = _('contact_us_message')
        verbose_name_plural = _('contact_us_messages')

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, default=1,
                                          related_name='messages')

    name = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    message = models.TextField(null=True)


class DocumentCategory(models.Model):

    class Meta:
        verbose_name = _('document_category')
        verbose_name_plural = _('document_categories')

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, default=1,
                                          related_name='document_categories')
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Document(models.Model):

    class Meta:
        verbose_name = _('document')
        verbose_name_plural = _('documents')

    category = models.ForeignKey(DocumentCategory, on_delete=models.CASCADE, default=1,
                                 related_name='category_documents')
    name = models.CharField(max_length=100, null=True)
    file = models.FileField(upload_to='checkcashing/documents', blank=True, null=True)

    def __str__(self):
        return self.name

highschooledu/highschooledu/apps/checkcashingchicago/views.py
from django.shortcuts import render
from ..webcompanies.models import WebCompanies
from django.core.mail import EmailMessage
from django.http import JsonResponse
from ..webcompanies.WebCompanies import WebSiteCompany
from django.http import JsonResponse
from .models import CheckCashingWeb
from .models import Currency, Partner, Location, ContactUsMessages
from django.urls import reverse
from django.shortcuts import redirect


def home(request):
    wsc = WebSiteCompany(request, web_company_id=8)
    company_obj = wsc.site_company()
    locations = wsc.site_company('locations')
    currencies = wsc.site_company('currencies')
    partners = wsc.site_company('partners')
    return render(request, 'checkcashingchicago/home.html', {'company_obj': company_obj,
                                                             'currencies': currencies,
                                                             'locations': locations,
                                                             'partners': partners,
                                                             })


def location_detail(request, slug):
    company_obj = check_cashing(request)
    partners = Partner.objects.all()
    location = Location.objects.get(slug=slug)

    l_all = Location.objects.filter(check_cashing_web=company_obj).all()
    l_first = l_all[0]
    l_last = l_all[len(l_all)-1]

    next_l = None
    prev_l = None

    if l_first.id == location.id:
        next_l = (Location.objects.filter(id__gt=location.id).exclude(id=location.id).order_by('id').first())
    elif l_last.id == location.id:
        prev_l = (Location.objects.filter(id__lt=location.id).exclude(id=location.id).order_by('id').first())
    else:
        next_l = (Location.objects.filter(id__gt=location.id).exclude(id=location.id).order_by('id').first())
        prev_l = (Location.objects.filter(id__lt=location.id).exclude(id=location.id).order_by('id').first())

    return render(request, 'checkcashingchicago/location_detail.html', {'location': location,
                                                                        'company_obj': company_obj,
                                                                        'partners': partners,
                                                                        'prev_l': prev_l,
                                                                        'next_l': next_l
                                                                        })


def members_area_detail(request):
    company_obj = check_cashing(request)
    partners = Partner.objects.all()
    return render(request, 'checkcashingchicago/members_area_detail.html', {'company_obj': company_obj,
                                                                            'partners': partners,
                                                                            })


def post_password(request):
    company_obj = check_cashing(request)
    pass_word_ = request.POST.get('pass_word')
    members_password_ = company_obj.members_password

    if pass_word_ != members_password_:
        print('ko')
        rr = {'status': 'Wrong Password!'}
        return JsonResponse(rr)

    return render(request, 'checkcashingchicago/members_area_doc.html', {'company_obj': company_obj})


# not used we should delete it
def get_location(request):
    # locations = check_cashing(request, 'locations')
    rr = {}
    # print(locations)
    # for location in locations:
    #     print(location.image)
    #     rr[str(location.id)] = {
    #                             'location_heading': location.location_heading,
    #                             'order': location.order,
    #                             'image_url': location.image.url,
    #                             'location_info': location.location_info,
    #                             'data_ajax_id': location.data_ajax_id,
    #                             'grid_loop': location.grid_loop,
    #                             'grid_parity': location.grid_parity,
    #                             'south_suburbs_sort': location.south_suburbs_sort
    #                             }

    return JsonResponse(rr)


def post_contact_us(request):
    company_id_ = request.POST.get('company_id')
    contact_us_name = request.POST.get('contact_us_name')
    contact_us_email = request.POST.get('contact_us_email')
    contact_us_message = request.POST.get('contact_us_message')
    if contact_us_message == '':
        rr = {'status': 'a message!'}
    else:
        rr = {'status': 'got it'}
        try:
            company_ = CheckCashingWeb.objects.get(id=company_id_)
            email = EmailMessage("Email received from contact us.", contact_us_message, contact_us_email, [company_.contact_us_email])
            email.send()
            ContactUsMessages.objects.create(check_cashing_web=company_, name=contact_us_name, email=contact_us_email,
                                             message=contact_us_message)
            rr = {'status': 'Your message was received.\n\nThank you.'}
        except Exception as ee:
            rr = {'status': 'Error sending your massage'}
    return JsonResponse(rr)

highschooledu/highschooledu/apps/checkcashingchicago/templates/checkcashingchicago/members_area_detail.html
{% extends "base_checkcashingchicago.html" %}
{% load static %}

    {% block title %}
     <title>Member&#039;s Area - Chicago Financial Enterprise</title>
    {% endblock%}


    {% block body %}
     <body id="top" class="page-template-default page page-id-96 stretched lato lora " itemscope="itemscope" itemtype="https://schema.org/WebPage">
    {% endblock %}


    {% block body_content %}
    <div id="wrap_all">
     <header id="header" class=" header_color dark_bg_color  av_header_top av_logo_left av_main_nav_header av_menu_right av_slim av_header_sticky av_header_shrinking_disabled av_header_stretch_disabled av_mobile_menu_phone av_header_searchicon_disabled av_header_unstick_top_disabled av_seperator_big_border av_bottom_nav_disabled " role="banner" itemscope="itemscope" itemtype="https://schema.org/WPHeader">
       <a id="advanced_menu_toggle" href="#" aria-hidden="true" data-av_icon="" data-av_iconfont="entypo-fontello"></a>
       <a id="advanced_menu_hide" href="#" aria-hidden="true" data-av_icon="" data-av_iconfont="entypo-fontello"></a>
       <div id="header_main" class="container_wrap container_wrap_logo">
           <div class="container av-logo-container">
               <div class="inner-container">
                   <strong class="logo">
                       <a href="{% url 'checkcashingchicago:home' %}">
                           <img height="100" width="300" src="{{ company_obj.logo_image.url }}" alt="Chicago Financial Enterprise"/></a>
                   </strong>
                   <nav class="main_menu" data-selectname="Select a page" role="navigation" itemscope="itemscope" itemtype="https://schema.org/SiteNavigationElement">
                       <div class="avia-menu av-main-nav-wrap">
                           <ul id="avia-menu" class="menu av-main-nav">
                               <li id="menu-item-270" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-top-level menu-item-top-level-1">
                                   <a href="{% url 'checkcashingchicago:home' %}#about" itemprop="url">
                                       <span class="avia-bullet"></span>
                                       <span class="avia-menu-text">About</span>
                                       <span class="avia-menu-fx">
                                           <span class="avia-arrow-wrap">
                                               <span class="avia-arrow"></span>
                                           </span>
                                       </span>
                                   </a>
                               </li>
                               <li id="menu-item-271" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-top-level menu-item-top-level-2">
                                   <a href="{% url 'checkcashingchicago:home' %}#locations" itemprop="url">
                                       <span class="avia-bullet"></span>
                                       <span class="avia-menu-text">Locations</span>
                                       <span class="avia-menu-fx">
                                           <span class="avia-arrow-wrap">
                                               <span class="avia-arrow"></span>
                                           </span>
                                       </span>
                                   </a>
                               </li>
                               <li id="menu-item-333" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-top-level menu-item-top-level-3">
                                   <a href="{% url 'checkcashingchicago:home' %}#contact" itemprop="url">
                                       <span class="avia-bullet"></span>
                                       <span class="avia-menu-text">Contact</span>
                                       <span class="avia-menu-fx">
                                           <span class="avia-arrow-wrap">
                                               <span class="avia-arrow"></span>
                                           </span>
                                       </span>
                                   </a>
                               </li>
                           </ul>
                       </div>
                   </nav>
               </div>
           </div><!-- end container_wrap-->
       </div>
       <div class="header_bg"></div><!-- end header -->
   </header>
    </div>
    <div id="main" data-scroll-offset="88">
		<div class="container_wrap container_wrap_first main_color fullsize">
			<div class="container">
				<main class="template-page content  av-content-full alpha units" role="main" itemprop="mainContentOfPage">
					<article class="post-entry post-entry-type-page post-entry-96" itemscope="itemscope" itemtype="https://schema.org/CreativeWork">
						<div class="entry-content-wrapper clearfix">
							<header class="entry-content-header"></header>
							<div style="margin-top:90px" class="entry-content" itemprop="text" id="container_">
								<form action="" class="post-password-form" method="post">
                                    <p>This content is password protected. To view it please enter your password below:</p>
									<p>
										<label for="pwbox-96">Password:
                                            <input name="post_password" id="pwbox-96" type="password" size="20"/></label>
										<input type="button" name="Submit" value="Enter"
                                               company_id="{{company_obj.id}}" onclick="check_password(event)"/>
									</p>
								</form>
							</div>
							<footer class="entry-footer"></footer>
						</div>
					</article><!--end post-entry-->
					<!--end content-->
				</main>
			</div><!--end container-->
		</div><!-- close default .container_wrap element -->
        <!-- end main -->
	</div>
    <script>
        function check_password(event)
        {
         elm = event.target
         input = document.getElementById("pwbox-96")
         password_ = input.value
         company_id_ = elm.getAttribute("company_id")

  $.post("{% url 'checkcashingchicago:post_password'%}",
    {
      company_id : company_id_,
      pass_word : password_
    },
    function(data){
     try {
      if (data['status'])
      {
       alert(data['status'])
      } else
      {
        var elm_container = document.getElementById('container_')
        elm_container.innerHTML = data
      }
     } catch (err) {alert(err)}

    }
  ).fail(function(error) { alert(error.responseJSON) });


        }
    </script>
    {% endblock %}

highschooledu/highschooledu/apps/checkcashingchicago/templates/checkcashingchicago/members_area_doc.html
<ul>
{% for category in company_obj.document_categories.all %}
    <li>
        {{ category }}
        <ol>
            {% for document in category.category_documents.all %}
              <li><a href="{{document.file.url}}"> {{ document }}</a></li>
            {% endfor %}
        </ol>
    </li>
{% endfor %}
</ul>

highschooledu/highschooledu/apps/checkcashingchicago/templates/checkcashingchicago/tem.html
<span class="entry-image">
	<img width="80" height="80" src="https://web.archive.org/web/20180817111928im_/http://checkcashingchicago.com/wp-content/uploads/2014/09/Sibley-Blvd-at-the-Calumet-Expwy-CE-41-80x80.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt=""
		 srcset="{{prev_l.image.url}} 80w,
		 {{prev_l.image.url}} 36w,
		 {{prev_l.image.url}} 180w,
		 {{prev_l.image.url}} 120w,
		 {{prev_l.image.url}} 450w"
		 sizes="(max-width: 80px) 100vw, 80px">
</span>

<div class="avia-slideshow-arrows avia-slideshow-controls">
<a href="#prev" class="prev-slide" aria-hidden="true" data-av_icon="" data-av_iconfont="entypo-fontello">Previous</a>
<a href="#next" class="next-slide" aria-hidden="true" data-av_icon="" data-av_iconfont="entypo-fontello">Next</a>
</div>

<a class="avia-post-nav avia-post-next with-image" href="https://web.archive.org/web/20180817113205/http://checkcashingchicago.com/Locations/sibley-blvd-at-the-calumet-expwy/">    <span class="label iconfont" aria-hidden="true" data-av_icon="" data-av_iconfont="entypo-fontello"></span>
	<span class="entry-info-wrap">
		<span class="entry-info">
			<span class="entry-image">
				<img width="80" height="80" src="https://web.archive.org/web/20180817113205im_/http://checkcashingchicago.com/wp-content/uploads/2014/09/Sibley-Blvd-at-the-Calumet-Expwy-CE-41-80x80.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt=""
					 srcset="https://web.archive.org/web/20180817113205im_/http://checkcashingchicago.com/wp-content/uploads/2014/09/Sibley-Blvd-at-the-Calumet-Expwy-CE-41-80x80.jpg 80w, https://web.archive.org/web/20180817113205im_/http://checkcashingchicago.com/wp-content/uploads/2014/09/Sibley-Blvd-at-the-Calumet-Expwy-CE-41-36x36.jpg 36w,
					 https://web.archive.org/web/20180817113205im_/http://checkcashingchicago.com/wp-content/uploads/2014/09/Sibley-Blvd-at-the-Calumet-Expwy-CE-41-180x180.jpg 180w,
					 https://web.archive.org/web/20180817113205im_/http://checkcashingchicago.com/wp-content/uploads/2014/09/Sibley-Blvd-at-the-Calumet-Expwy-CE-41-120x120.jpg 120w,
					 https://web.archive.org/web/20180817113205im_/http://checkcashingchicago.com/wp-content/uploads/2014/09/Sibley-Blvd-at-the-Calumet-Expwy-CE-41-450x450.jpg 450w"
					 sizes="(max-width: 80px) 100vw, 80px"></span>
			<span class="entry-title">Sibley Blvd at the Calumet Expwy</span>
		</span>
	</span>
</a>














{% for l in locations %}
									  <div data-ajax-id="{{l.data_ajax_id}}" class=" grid-entry flex_column isotope-item all_sort no_margin post-entry post-entry-{{l.data_ajax_id}} grid-entry-overview grid-loop-{{forloop.counter}} grid-parity-{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %} av_one_third {% if forloop.counter0|divisibleby:3 %}first{% endif %} {{l.region.slug}}_sort default_av_fullwidth ">
										  <article class="main_color inner-entry" itemscope="itemscope" itemtype="https://schema.org/CreativeWork">
											  <a href="{{ l.get_absolute_url }}" title="{{l.location_heading}}" data-rel="grid-1" class="grid-image avia-hover-fx">
												  <img width="1500" height="630" src="{{l.image.url}}" class="attachment-featured_large size-featured_large wp-post-image" alt="location"
													   srcset="{{l.image.url}}"/>
											  </a>

											  <div class="grid-content">
												  <div class="avia-arrow"></div>
												  <header class="entry-content-header">
													  <h3 class="grid-entry-title entry-title" itemprop="headline">
														  <a href="{{ l.get_absolute_url }}" title="{{l.location_heading}}">{{l.location_heading}}</a>
													  </h3>
												  </header>
												  <div class="grid-entry-excerpt entry-content" itemprop="text">
													  {{l.address1}}<br>
													  {{l.address2}}<br>
													  {{l.address3}}<br>
													  {{l.address4}}
												  </div>
											  </div>
											  <footer class="entry-footer"></footer>
										  </article>
									  </div>
								  {% endfor %}














     {% if prev_l %}
       <a class="avia-post-nav avia-post-prev with-image" href="{{ prev_l.get_absolute_url }}">
           <span class="label iconfont" aria-hidden="true"  data-av_iconfont="entypo-fontello"><i class="fa fa-angle-left"></i></span>
           <span class="entry-info-wrap">
               <span class="entry-info">
                   <span class="entry-title">{{prev_l.location_detail_title}}</span>
                   <span class="entry-image">
                       <img width="80" height="80" src="{{prev_l.image.url}}" class="attachment-thumbnail size-thumbnail wp-post-image" alt="{{prev_l.location_detail_title}}"  sizes="(max-width: 80px) 100vw, 80px">
                   </span>
               </span>
           </span>
       </a>
     {% endif %}



       {% if next_l %}
       <a class="avia-post-nav avia-post-next with-image" href="{{ next_l.get_absolute_url }}">
           <span class="label iconfont" aria-hidden="true"  data-av_iconfont="entypo-fontello"><i class="fa fa-angle-right"></i></span>
           <span class="entry-info-wrap">
               <span class="entry-info">
                   <span class="entry-image">
                       <img width="80" height="80" src="{{next_l.image.url}}" class="attachment-thumbnail size-thumbnail wp-post-image" alt="{{next_l.location_detail_title}};"  sizes="(max-width: 80px) 100vw, 80px">
                   </span>
                   <span class="entry-title">{{next_l.location_detail_title}}</span>
               </span>
           </span>
       </a>
       {% endif %}