highschooledu/highschooledu/apps/checkcashingchicago/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (home, get_location, location_detail, post_contact_us, members_area_detail,
                    post_password)

app_name = 'checkcashingchicago'

urlpatterns = [
    path('', home, name='home'),
    path('get_courses', get_location, name='get_location'),
    path('location_detail/<slug:slug>/', location_detail, name='location_detail'),
    path('members_area_detail', members_area_detail, name='members_area_detail'),
    path('post_contact_us', post_contact_us, name='post_contact_us'),
    path('post_password', post_password, name='post_password'),
]

highschooledu/highschooledu/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]


urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path(r'core/', include('highschooledu.apps.core.urls')),
    # path(r'e/', include('highschooledu.apps.education.urls')),
    path(r'c/', include('highschooledu.apps.checkcashingchicago.urls')),
    path(r'p/', include('highschooledu.apps.portfolio.urls')),

    path(r'search/', include('highschooledu.apps.search.urls')),
    path(r'webcompanies/', include('highschooledu.apps.webcompanies.urls')),
    path("", include("cms.urls"))
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

highschooledu/highschooledu/apps/checkcashingchicago/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from cms.models.fields import PlaceholderField


class CheckCashingWeb(models.Model):

    class Meta:
        verbose_name = _('check cashing')
        verbose_name_plural = _('check cashing')
        ordering = ['order']

    order = models.IntegerField(default=1000, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    domain_name = models.CharField(max_length=100, null=True, blank=True)
    main_image = models.ImageField(upload_to='checkcashing/', blank=True, null=True)
    logo_image = models.ImageField(upload_to='checkcashing/', blank=True, null=True)
    background_location_image = models.ImageField(upload_to='location/', blank=True, null=True)
    background_currency_image = models.ImageField(upload_to='currency/', blank=True, null=True)
    main_title = models.CharField(max_length=100, null=True)
    footer_main_title = models.CharField(max_length=100, null=True)
    main_sub_title = models.CharField(max_length=100, null=True)
    location_title = models.CharField(max_length=100, null=True)
    partner_title = models.CharField(max_length=100, null=True)
    main_sub_description = models.CharField(max_length=500, null=True)
    check_cashing_application = models.FileField(upload_to='checkcashing/', blank=True, null=True)
    application_for_employment = models.FileField(upload_to='checkcashing/', blank=True, null=True)
    copy_right_year = models.CharField(max_length=4, null=True)
    contact_us_email = models.CharField(max_length=100, null=True)
    members_password = models.CharField(max_length=100, default='101')

    def __str__(self):
        return self.name


class LocationRegion(models.Model):

    class Meta:
        verbose_name = _('location_region')
        verbose_name_plural = _('location_regions')
        ordering = ['order']

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, related_name='location_regions')
    order = models.IntegerField(default=1000, blank=True)
    region_title = models.CharField(max_length=100, null=True)
    slug = models.SlugField(max_length=250, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.region_title)
        super(LocationRegion, self).save(*args, **kwargs)

    def __str__(self):
        return self.region_title


class Location(models.Model):

    class Meta:
        verbose_name = _('location')
        verbose_name_plural = _('locations')
        ordering = ['order']

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE,
                                          related_name='locations')
    region = models.ForeignKey(LocationRegion, on_delete=models.CASCADE, blank=True, null=True,
                               related_name='region_locations')
    order = models.IntegerField(default=1000, blank=True)
    image = models.ImageField(upload_to='location/', blank=True, null=True)
    location_heading = models.CharField(max_length=100, null=True)
    location_detail_title = models.CharField(max_length=100, null=True)
    address1 = models.CharField(max_length=50, null=True)
    address2 = models.CharField(max_length=50, null=True)
    address3 = models.CharField(max_length=50, null=True)
    address4 = models.CharField(max_length=50, null=True)
    working_hours1 = models.CharField(max_length=50, blank=True, null=True)
    working_hours2 = models.CharField(max_length=50, blank=True, null=True)
    working_hours3 = models.CharField(max_length=50, blank=True, null=True)
    working_hours4 = models.CharField(max_length=50, blank=True, null=True)
    data_ajax_id = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(max_length=250, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.location_heading)
        super(Location, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('checkcashingchicago:location_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.location_heading


class Service(models.Model):

    class Meta:
        verbose_name = _('service')
        verbose_name_plural = _('services')
        ordering = ['order']

    location = models.ManyToManyField(Location, related_name='services')
    order = models.IntegerField(default=1000, blank=True)
    title = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=800, null=True)


class Currency(models.Model):

    class Meta:
        verbose_name = _('currency')
        verbose_name_plural = _('currencies')
        ordering = ['order']

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, default=1,
                                          related_name='currencies')
    order = models.IntegerField(default=1000, blank=True)
    image = models.ImageField(upload_to='currency/', blank=True, null=True)
    currency_header = models.CharField(max_length=100, null=True)
    currency_description = models.CharField(max_length=500, null=True)
    image_id = models.IntegerField(default=0)
    currency_loop = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)


class Partner(models.Model):

    class Meta:
        verbose_name = _('partner')
        verbose_name_plural = _('partners')
        ordering = ['order']

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, default=1,
                                          related_name='partners')
    order = models.IntegerField(default=1000, blank=True)
    partner_image = models.ImageField(upload_to='partner/', blank=True, null=True)
    partner_description = models.CharField(max_length=100, null=True)
    partner_link = models.CharField(max_length=100, null=True)
    image_id = models.IntegerField(default=0)
    image_width = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)


class ContactUsMessages(models.Model):

    class Meta:
        verbose_name = _('contact_us_message')
        verbose_name_plural = _('contact_us_messages')

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, default=1,
                                          related_name='messages')

    name = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    message = models.TextField(null=True)


class DocumentCategory(models.Model):

    class Meta:
        verbose_name = _('document_category')
        verbose_name_plural = _('document_categories')

    check_cashing_web = models.ForeignKey(CheckCashingWeb, on_delete=models.CASCADE, default=1,
                                          related_name='document_categories')
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Document(models.Model):

    class Meta:
        verbose_name = _('document')
        verbose_name_plural = _('documents')

    category = models.ForeignKey(DocumentCategory, on_delete=models.CASCADE, default=1,
                                 related_name='category_documents')
    name = models.CharField(max_length=100, null=True)
    file = models.FileField(upload_to='checkcashing/documents', blank=True, null=True)

    def __str__(self):
        return self.name

highschooledu/highschooledu/apps/checkcashingchicago/views.py
from django.shortcuts import render
from ..webcompanies.models import WebCompanies
from django.core.mail import EmailMessage
from django.http import JsonResponse
from ..webcompanies.WebCompanies import WebSiteCompany
from django.http import JsonResponse
from .models import CheckCashingWeb
from .models import Currency, Partner, Location, ContactUsMessages
from django.urls import reverse
from django.shortcuts import redirect


def home(request):
    wsc = WebSiteCompany(request, web_company_id=8)
    company_obj = wsc.site_company()
    locations = wsc.site_company('locations')
    currencies = wsc.site_company('currencies')
    partners = wsc.site_company('partners')
    return render(request, 'checkcashingchicago/home.html', {'company_obj': company_obj,
                                                             'currencies': currencies,
                                                             'locations': locations,
                                                             'partners': partners,
                                                             })


def location_detail(request, slug):
    company_obj = check_cashing(request)
    partners = Partner.objects.all()
    location = Location.objects.get(slug=slug)

    l_all = Location.objects.filter(check_cashing_web=company_obj).all()
    l_first = l_all[0]
    l_last = l_all[len(l_all)-1]

    next_l = None
    prev_l = None

    if l_first.id == location.id:
        next_l = (Location.objects.filter(id__gt=location.id).exclude(id=location.id).order_by('id').first())
    elif l_last.id == location.id:
        prev_l = (Location.objects.filter(id__lt=location.id).exclude(id=location.id).order_by('id').first())
    else:
        next_l = (Location.objects.filter(id__gt=location.id).exclude(id=location.id).order_by('id').first())
        prev_l = (Location.objects.filter(id__lt=location.id).exclude(id=location.id).order_by('id').first())

    return render(request, 'checkcashingchicago/location_detail.html', {'location': location,
                                                                        'company_obj': company_obj,
                                                                        'partners': partners,
                                                                        'prev_l': prev_l,
                                                                        'next_l': next_l
                                                                        })


def members_area_detail(request):
    company_obj = check_cashing(request)
    partners = Partner.objects.all()
    return render(request, 'checkcashingchicago/members_area_detail.html', {'company_obj': company_obj,
                                                                            'partners': partners,
                                                                            })


def post_password(request):
    company_obj = check_cashing(request)
    pass_word_ = request.POST.get('pass_word')
    members_password_ = company_obj.members_password

    if pass_word_ != members_password_:
        print('ko')
        rr = {'status': 'Wrong Password!'}
        return JsonResponse(rr)

    return render(request, 'checkcashingchicago/members_area_doc.html', {'company_obj': company_obj})


# not used we should delete it
def get_location(request):
    # locations = check_cashing(request, 'locations')
    rr = {}
    # print(locations)
    # for location in locations:
    #     print(location.image)
    #     rr[str(location.id)] = {
    #                             'location_heading': location.location_heading,
    #                             'order': location.order,
    #                             'image_url': location.image.url,
    #                             'location_info': location.location_info,
    #                             'data_ajax_id': location.data_ajax_id,
    #                             'grid_loop': location.grid_loop,
    #                             'grid_parity': location.grid_parity,
    #                             'south_suburbs_sort': location.south_suburbs_sort
    #                             }

    return JsonResponse(rr)


def post_contact_us(request):
    company_id_ = request.POST.get('company_id')
    contact_us_name = request.POST.get('contact_us_name')
    contact_us_email = request.POST.get('contact_us_email')
    contact_us_message = request.POST.get('contact_us_message')
    if contact_us_message == '':
        rr = {'status': 'a message!'}
    else:
        rr = {'status': 'got it'}
        try:
            company_ = CheckCashingWeb.objects.get(id=company_id_)
            email = EmailMessage("Email received from contact us.", contact_us_message, contact_us_email, [company_.contact_us_email])
            email.send()
            ContactUsMessages.objects.create(check_cashing_web=company_, name=contact_us_name, email=contact_us_email,
                                             message=contact_us_message)
            rr = {'status': 'Your message was received.\n\nThank you.'}
        except Exception as ee:
            rr = {'status': 'Error sending your massage'}
    return JsonResponse(rr)

highschooledu/highschooledu/apps/checkcashingchicago/templates/base_checkcashingchicago0.html
{% load static i18n cms_tags menu_tags sekizai_tags thumbnail %}

<!DOCTYPE html>
<html lang="en-US" prefix="og: http://ogp.me/ns#" class=" html_stretched responsive av-preloader-disabled av-default-lightbox  html_header_top html_logo_left html_main_nav_header html_menu_right html_slim html_header_sticky html_header_shrinking_disabled html_header_transparency html_mobile_menu_phone html_disabled html_header_searchicon_disabled html_content_align_center html_header_unstick_top_disabled html_header_stretch_disabled html_entry_id_265 ">
<head>
  {% block title %}<title>Title</title>{% endblock%}
  {% block meta %}{% endblock %}
  {% block links %} {% endblock %}
  {% block style %} {% endblock %}
  {% block scripts %} {% endblock %}
  {% render_block "css" %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</head>

  {% block body %}
  {% endblock %}

  <div id="wrap_all">
	  <div id="main" data-scroll-offset="88">
        {% block body_content %}
        {% endblock %}
	 </div><!-- end wrap_all -->
	  <div class="container_wrap footer_color" id="footer">
			  <div class="container">
				  <div class="flex_column   first el_before_">
					  <section id="text-2" class="widget clearfix widget_text">
						  <div class="textwidget">
							  <p style="text-align: center; font-size: 33px;">{{company_obj.partner_title}}</p>
							  <div style="text-align: center;">
								  {% for partner in partners %}
								  <div style="display: inline-block; padding: 15px;{% if  partner.id == 4 %} position: relative; top: 24px;{% endif %}">
									  <a href="{{partner.partner_link}}" target="_blank">
										  <img class="aligncenter wp-image-{{partner.image_id}}"
											   src="{{partner.partner_image.url}}" alt="cce" width="{{partner.image_width}}" height="90"/>
										  {% if partner.id == 4 %}
										  <br>
										  <span style="position: relative; top: -50px;">{{partner.partner_description}}</span>
										  {% endif %}
									  </a>
								  </div>
								  {% endfor %}
							  </div>
						  </div>
						  <span class="seperator extralight-border"></span>
					  </section>
				  </div>
			  </div><!-- ####### END FOOTER CONTAINER ####### -->
		  </div>
	  <footer class="container_wrap socket_color" id="socket" role="contentinfo" itemscope="itemscope" itemtype="https://schema.org/WPFooter">
			  <div class="container">
				  <span class="copyright">© Copyright {{ company_obj.copy_right_year}} - {{company_obj.footer_main_title}}  </span>
				  <nav class="sub_menu_socket" role="navigation" itemscope="itemscope" itemtype="https://schema.org/SiteNavigationElement">
					  <div class="avia3-menu">
						  <ul id="avia3-menu" class="menu">
							  <li id="menu-item-268" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-top-level menu-item-top-level-1">
								  <a href="{% url 'checkcashingchicago:members_area_detail' %}" itemprop="url">
									  <span class="avia-bullet"></span>
									  <span class="avia-menu-text">Member&#8217;s Area</span>
									  <span class="avia-menu-fx">
										  <span class="avia-arrow-wrap">
											  <span class="avia-arrow"></span>
										  </span>
									  </span>
								  </a>
							  </li>
							  <li id="menu-item-275" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-top-level menu-item-top-level-2">
								  <a target="_blank" href="{{ company_obj.check_cashing_application.url }}" itemprop="url">
									  <span class="avia-bullet"></span>
									  <span class="avia-menu-text">Commercial Check Cashing Application</span>
									  <span class="avia-menu-fx">
										  <span class="avia-arrow-wrap">
											  <span class="avia-arrow"></span>
										  </span>
									  </span>
								  </a>
							  </li>
							  <li id="menu-item-272" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-top-level menu-item-top-level-3">
								  <a target="_blank" href="{{ company_obj.application_for_employment.url }}" itemprop="url">
									  <span class="avia-bullet"></span>
									  <span class="avia-menu-text">Application for Employment</span>
									  <span class="avia-menu-fx">
										  <span class="avia-arrow-wrap">
											  <span class="avia-arrow"></span>
										  </span>
									  </span>
								  </a>
							  </li>
						  </ul>
					  </div>
				  </nav>
			  </div><!-- ####### END SOCKET CONTAINER ####### -->
		  </footer><!-- end main -->
	       <a href="#top" title="Scroll to top" id="scroll-top-link" aria-hidden="true" data-av_iconfont="entypo-fontello">
		     <i class="fa fa-angle-up"></i>
		  <span class="avia_hidden_link_text">Scroll to top</span>
	      </a>
<!--	  <a href="#top" title="Scroll to top" id="scroll-top-link" aria-hidden="true" data-av_icon="" data-av_iconfont="entypo-fontello">-->
<!--		  <span class="avia_hidden_link_text">Scroll to top</span>-->
<!--	  </a>-->
	  <div id="fb-root"></div>
  </div>



<!--
     FILE ARCHIVED ON 03:59:27 Aug 05, 2018 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 06:27:54 Jun 17, 2021.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
-->
<!--
playback timings (ms):
  captures_list: 138.865
  exclusion.robots: 0.333
  exclusion.robots.policy: 0.32
  RedisCDXSource: 25.964
  esindex: 0.011
  LoadShardBlock: 85.683 (3)
  PetaboxLoader3.datanode: 79.345 (4)
  CDXLines.iter: 22.467 (3)
  load_resource: 78.982
  PetaboxLoader3.resolve: 34.354
-->



  {% block js %}
  {% endblock %}

  <p id="demo"></p>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/npm/cookie/js.cookie.min.js' %}"></script>
  <script>
  var csrftoken = Cookies.get('csrftoken');
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });

  $(document).ready(function(){
    post_ajax_create_action = function (verb_="", app_="", model_, obj_slug_=null, pkey_=null) {
      $.post(link_create_action,
        {
          verb: verb_,
          app: app_,
          model: model_,
          obj_slug: obj_slug_,
          pkey: pkey_
        },
        function(data){
            alert(data["status"])
        }
      );
    }

    {% block domready %}
    {% endblock %}
  });
</script>
        {% render_block "js" %}
</body>
</html>